import {
  defineConfig,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
} from "unocss";

export default defineConfig({
  presets: [
    presetUno(),
    presetWebFonts({
      provider: "google",
      fonts: {
        sans: "Sora",
        mono: ["Poppins"],
        roboto: "Roboto",
      },
    }),
    presetIcons(),
    presetTypography(),
  ],
  safelist: [
    'scale-102',
    'scale-105',
    'scale-110',
    'shadow-3xl',
    'line-clamp-2',
    'animate-spin',
    'i-tabler-flag-filled',
    'i-tabler-search',
    'i-tabler-loader-2',
    'i-tabler-info-circle',
    'i-tabler-alert-circle',
    'i-tabler-alert-triangle',
    'i-tabler-tag',
    'i-tabler-arrow-right',
    'i-tabler-database',
    'i-tabler-package',
    'i-tabler-heart-handshake',
    'i-tabler-users',
    'i-tabler-peace',
    'i-tabler-target',
    'i-tabler-burger',
    'i-tabler-spray',
    'i-tabler-cookie',
    'i-tabler-cup',
    'i-tabler-salt',
    'i-tabler-sparkles',
    'i-tabler-coffee',
    'i-tabler-flower',
    'i-tabler-milk',
    'i-tabler-shirt',
    'i-tabler-building-store',
    'i-tabler-shield',
    'i-tabler-perfume',
    'i-tabler-baby-carriage',
    'i-tabler-medical-cross',
    'i-tabler-shopping-cart',
    'i-tabler-bottle',
    'i-tabler-device-tv',
    'i-tabler-category',
    'i-tabler-circle-check',
  ],
  theme: {
    extend: {
      boxShadow: {
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
      },
    },
  },
});
